import type { IntentRule } from './intent-router.types';

export const intentRules: IntentRule[] = [
  {
    intent: 'BOOKING_CANCEL',
    key: 'booking_cancel',
    phrases: [
      'cancelar cita',
      'quiero cancelar mi cita',
      'cancelar mi cita',
      'quiero anular mi cita',
      'anular mi cita',
      'anular cita',
      'cancela mi cita',
      'cancela la cita',
      'cancela mi hora',
      'quiero cancelar la hora',
      'no podre venir',
      'no puedo venir',
      'no puedo asistir',
      'anula mi hora',
      'cancelar reserva',
      'dar de baja la cita',
    ],
  },
  {
    intent: 'BOOKING_CHANGE',
    key: 'booking_change',
    phrases: [
      'cambiar cita',
      'quiero cambiar mi cita',
      'cambiar mi cita',
      'modificar cita',
      'mover la cita',
      'quiero mover mi cita',
      'mover mi cita',
      'cambiar la hora',
      'cambiar mi hora',
      'cambiar el dia',
      'puedo cambiar mi cita',
      'no puedo venir a esa hora',
      'mejor otro dia',
      'pasamela',
      'aplazar cita',
      'reprogramar cita',
    ],
  },
  {
    intent: 'BOOKING_REQUEST',
    key: 'booking_request',
    phrases: [
      'quiero cita',
      'pedir cita',
      'pedir hora',
      'quiero pedir hora',
      'necesito cita',
      'reservar cita',
      'quiero reservar',
      'teneis hora',
      'teneis hueco',
      'hay hueco',
      'disponibilidad',
      'puedo venir',
      'me das cita',
      'me puedes dar cita',
      'quiero una manicura',
      'quiero un masaje',
      'quiero una pedicura',
      'tienes algo libre',
      'tenes algo libre',
      'hora para manana',
    ],
  },
  {
    intent: 'PRICE_REQUEST',
    key: 'price_request',
    phrases: [
      'cuanto cuesta',
      'que precio',
      'precio de',
      'cuanto vale',
      'tarifas',
      'lista de precios',
      'cuanto me sale',
      'cuanto cobrais',
      'cuanto cobras',
    ],
  },
  {
    intent: 'HOURS_REQUEST',
    key: 'hours_request',
    phrases: [
      'horario',
      'horarios',
      'a que hora abris',
      'a que hora cerrais',
      'abris el sabado',
      'estais abiertos',
      'horario de apertura',
      'horario de cierre',
      'abren por la tarde',
      'abris por la tarde',
    ],
  },
];
